apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
spec:
  replicas: 3
  selector:
    app: httpd-rc
  template:
    metadata:
      name: httpd-rc
      labels:
        app: httpd-rc
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
