apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rc
  labels:
    name: httpd-rc
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      name: httpd-rc
  template:
    metadata:
      labels:
        name: httpd-rc
    spec:
      containers:
      - name: httpd-rc
        image: httpd
        ports:
        - name: web
          containerPort:  80
          protocol: TCP