apiVersion: v1
kind: Pod
metadata:
  name: "mysql-pod"
  namespace: mysql-ns
  labels:
    app: "mysql-pod"
spec:
  containers:
  - name: "mysql-pod"
    image: "mysql:latest"
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: myssql-pass
          key: password
    ports:
      - containerPort: 3306
        name: mysql