apiVersion: v1
kind: Secret
metadata:
   name: db-credentials
data:
  mysql-password: cGFzc3dvcmQxMjM=
  mysql-root-password: cGFzc3dvcmQxMjM=
  mysql-user: dXNlcjEyMw==
gfeb278@cloudshell:~/Kubernetes-practice (summer-topic-376606)$ cat deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: db-credentials
                key: mysql-root-password
        ports:
        - containerPort: 3306