apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-pod
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_DB
          value: mydb