apiVersion: v1
kind: Pod
metadata:
  name: "postgres-pod"
  namespace: default
  labels:
    app: "postgres-pod"
spec:
  containers:
  - name: postgres-pod
    image: "postgres"
    env:
    - name: POSTGRES_PASSWORD
      value: db@10
    - name: POSGRES_USER
      value: db@10
    - name: POSTGRES_DB
      value: mydb
